#!/usr/bin/env bash
# load-ssm-env.sh
#
# Reads all parameters from AWS SSM Parameter Store at /ai-tutor/prod/ and
# writes them to .env on EC2. Called during each deployment so that secret
# updates in SSM take effect without manual SSH.
#
# Usage (on EC2 or from SSM Run Command):
#   ./scripts/load-ssm-env.sh
#
# Environment overrides:
#   SSM_PATH    SSM path prefix   (default: /ai-tutor/prod/)
#   ENV_FILE    Output .env path  (default: /home/ubuntu/AI-Tutor-Agent/.env)
#   AWS_REGION  AWS region        (default: ap-southeast-2)
#
# To update a secret without redeploying code:
#   aws ssm put-parameter --region ap-southeast-2 \
#     --name /ai-tutor/prod/DEEPGRAM_SECRET_KEY \
#     --value "new-value" --type SecureString --overwrite
#   # Then either re-run deploy or SSH and run this script + restart Docker

set -euo pipefail

SSM_PATH="${SSM_PATH:-/ai-tutor/prod/}"
ENV_FILE="${ENV_FILE:-/home/ubuntu/AI-Tutor-Agent/.env}"
REGION="${AWS_REGION:-ap-southeast-2}"

echo "Reading SSM parameters from ${SSM_PATH} (region: ${REGION})"

TMP_JSON=$(mktemp)
TMP_ENV=$(mktemp)
trap 'rm -f "${TMP_JSON}" "${TMP_ENV}"' EXIT

aws ssm get-parameters-by-path \
  --path "${SSM_PATH}" \
  --with-decryption \
  --recursive \
  --region "${REGION}" \
  --output json > "${TMP_JSON}"

# Convert SSM JSON to .env format
# Pass SSM_PATH via env so the heredoc can be single-quoted (prevents bash
# from interpreting backslashes and $ inside the Python code).
SSM_PATH="${SSM_PATH}" python3 - "${TMP_JSON}" "${TMP_ENV}" <<'PYEOF'
import sys, json, os

tmp_json    = sys.argv[1]
tmp_env     = sys.argv[2]
path_prefix = os.environ["SSM_PATH"]

with open(tmp_json) as f:
    data = json.load(f)

params = data.get("Parameters", [])

if not params:
    print(f"ERROR: No SSM parameters found at {path_prefix}", file=sys.stderr)
    print("Run 'terraform apply' in terraform/assessment/ and add secrets:", file=sys.stderr)
    print("  aws ssm put-parameter --name /ai-tutor/prod/AUTH_JWT_SECRET --value '...' --type SecureString", file=sys.stderr)
    sys.exit(1)

lines = [
    "# Generated by scripts/load-ssm-env.sh from AWS SSM Parameter Store",
    "# Do not edit manually — update via: aws ssm put-parameter --overwrite",
    "",
]

for p in sorted(params, key=lambda x: x["Name"]):
    key   = p["Name"]
    value = p["Value"]

    if key.startswith(path_prefix):
        key = key[len(path_prefix):]

    # No quoting — all current values are single-word tokens, URLs, or region strings.
    # If a value contains whitespace, wrap it here.
    if any(c in value for c in (" ", "\t", "#")):
        value = '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

    lines.append(f"{key}={value}")

with open(tmp_env, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Loaded {len(params)} parameters from SSM")
PYEOF

# Validate that required keys are present
REQUIRED=(
  AUTH_JWT_SECRET
  DEEPGRAM_SECRET_KEY
  NEO4J_PASSWORD
  AWS_DEFAULT_REGION
  DYNAMODB_TABLE_NAME
  DYNAMODB_AUTH_USERS_TABLE
  DYNAMODB_ASSESSMENT_TABLE
)

MISSING=()
for key in "${REQUIRED[@]}"; do
  if ! grep -q "^${key}=" "${TMP_ENV}"; then
    MISSING+=("${key}")
  fi
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
  echo "ERROR: The following required SSM parameters are missing:" >&2
  for key in "${MISSING[@]}"; do
    echo "  ${SSM_PATH}${key}" >&2
  done
  echo "Add them with: aws ssm put-parameter --region ${REGION} --name '${SSM_PATH}KEY' --value '...' --type SecureString" >&2
  exit 1
fi

mv "${TMP_ENV}" "${ENV_FILE}"
echo "Wrote $(grep -c '=' "${ENV_FILE}") env vars to ${ENV_FILE}"
